/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>

#define RCC_IOPENR			(*(volatile unsigned int *)0x40021034)	// enable GPIO ports
#define RCC_APBENR1			(*(volatile unsigned int *)0x4002103C)  // offset 0x3C
#define RCC_APBENR2         (*(volatile unsigned int *)0x40021040)  // offset 0x40

#define GPIOA_MODER         (*(volatile unsigned int *)0x50000000)  // port A
#define GPIOB_MODER			(*(volatile unsigned int *)0x50000400)	// port b
#define GPIOB_AFRL			(*(volatile unsigned int *)0x50000420)	// offset 0x20
#define GPIOB_ODR           (*(volatile unsigned int *)0x50000414)  // offset 0x14

#define TIM2_CR1			(*(volatile unsigned int *)0x40000000)	// enable counter base address 0x4000000
#define TIM2_ARR			(*(volatile unsigned int *)0x4000002C)	// offset 0x2C PWM clock 16MHz / N
#define TIM2_CCER			(*(volatile unsigned int *)0x40000020)	// offset 0x20 Enable TIM2_CHx
#define TIM2_CCMR1			(*(volatile unsigned int *)0x40000018)	// offset = 0x18	select PWM mode
#define TIM2_CCR2			(*(volatile unsigned int *)0x40000038)	// offset 0x38  capture and compare channel 2
#define TIM2_PSC            (*(volatile unsigned int *)0x40000028)  // offset 0x28 clock prescalar

#define ADC_CR              (*(volatile unsigned int *)0x40012408)      // offset 0x08
#define ADC_CFGR1           (*(volatile unsigned int *)0x4001240C)      // offset 0x0C
#define ADC_CHSELR          (*(volatile unsigned int *)0x40012428)      // offset 0x28 channel selection
#define ADC_DR              (*(volatile unsigned int *)0x40012440)      // offset 0x40 data reg (reads converted data)
#define ADC_ISR             (*(volatile unsigned int *)0x40012400)      // BASE 0x4001 2400

// data mask
#define ADSTART (1<<2)  // start ADC conversion
#define ADEN    (1<<0)  // enable ADC
#define EOC (1<<2)      // flag f/end of conversion

int candleState = 0; // on/off = 1/0
int flickerDelay = 0;

void wait_ms(int ms) {
int i,j;
for(i=0;i<ms;i++) for(j=0;j<1340;j++);
}

int rngNum() {
    int r = rand();
    r = (r % 50) + 50;  // 0 - 49
    return r;          // return random num
}

// random flicker timer need new random num gen
int randomFlicker () {
    int flickerTime = rngNum();
    flickerTime = (flickerTime % 50) + 50;  // limit to (0 - 49) + 50 --> 50 - 99
    return flickerTime;
}

float readVolt() {
    ADC_CR |= ADSTART;   //start read
    while (!(ADC_ISR & EOC));  // while conversion is NOT done
    float volt = (ADC_DR & 0xFFFF); // read conversion
    float convert = (volt / 4095.0) * 3.3; // 2^12 (4095) is bit resolution of ADC, 3.3 is ADC ref voltage
    return convert;
}

void setDuty (int cycle) {
    TIM2_CCR2 = (TIM2_ARR * cycle) / 100;
}

void enableReg() {
    RCC_IOPENR |= (1<<0);   // port a enable ADC input
    RCC_IOPENR |= (1<<1);   // port b enable TIM2
    RCC_APBENR1 |= (1<<0);  // TIM2 enable

    GPIOA_MODER &= ~(3 << (2*0));   // clear PA0
    GPIOA_MODER |= (3 << (2*0));    // analog input?
    GPIOB_MODER &= ~(3 << (2*3));   // clear PB3
    GPIOB_MODER |= (2 << (2*3));    // set PB3 to AF mode
    GPIOB_AFRL &= ~(0xF << (4*3));  // clear AF register
    GPIOB_AFRL |= (2<<(4*3));       // AF2 (TIM2_CH2)
}

void enableADC() {
    RCC_APBENR2 |= (1 << 20);    // enable ADC clock
    // ADC volt regulator
    ADC_CHSELR = (1 << 0);  // selected channel f/input channel 2
    ADC_CR |= (1 << 28);    // volt regulator
    wait_ms(1);
    // ADC cal
    ADC_CR |= (1 << 31);    // start cal
    while (ADC_CR & (1<<31));
    // config ADC options as req'd
    ADC_CR |= ADEN;   // enable ADC
    while (!(ADC_ISR & 1)); //wait f/ADRDY
}

void enableTIM() {
    TIM2_PSC = (16-1);      // prescalar
    TIM2_ARR = 255;         // period
    TIM2_CCMR1 |= (6 << 12);    // PWM mode 1
    TIM2_CCER |= (1 << 4);  // ch 2 output bits may not be right
    TIM2_CR1 |= (1 << 0);   // counter enable
}

int main(void) {
    enableReg();
    enableTIM();
    enableADC();

    while(1) {
        float volt = readVolt();

        // candle logic
        if (volt > 1.0){    // volt threshold may not be correct if 3.3 ref volt is correct
            candleState = 1;
            //setDuty(100);  // test basic op on
        }
        else if (volt < .90) {
            candleState = 0;
            //setDuty(0);   // test basic op off
        }

        // random flicker
        if (candleState == 1) { //comment out until rngNum() if remade
            int cycle = randomFlicker();
            setDuty(cycle);
            flickerDelay = randomFlicker();
            wait_ms(flickerDelay);
        }
        else {
            setDuty(0);
        }
    }
}
